# Data Cleaning 

This notebook cleans the raw data available in data/raw and writes the clean version back to the folder data/processed.

In [70]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np 
from c08_farming_exit import config, features, data_cleaning, mappings

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [54]:
# #In case you want to run Stata in a cell using the magic command %%stata, initialize it first!
# from c08_farming_exit.stata_utils import init_stata
# init_stata()

In [71]:
COUNTRIES = {
    "Botswana": config.RAW_DATA_DIR / "Botswana",
    "Kenya":    config.RAW_DATA_DIR / "Kenya",
    "Namibia":  config.RAW_DATA_DIR / "Namibia",
    "Tanzania": config.RAW_DATA_DIR / "Tanzania",
    "Zambia":   config.RAW_DATA_DIR / "Zambia",
}

## 1. Database

In [72]:
#THE DATABASE CONSISTS OF ADULTS ONLY
database = []

for country, base_path in COUNTRIES.items():
    identifying_info    = data_cleaning.load_and_preprocess(base_path, f"{country}_identifying_info.csv",                  features.IDENTIFYING_INFO_2023)
    hh_members          = data_cleaning.load_and_preprocess(base_path, f"{country}_household_members_characterstics.csv",  features.HH_MEMBERS_2023)
    hh_members          = data_cleaning.create_education_features(hh_members)

    merge = identifying_info.merge(hh_members, on=["interview_key"], how="inner")
    
    filtered = merge[
        merge["relation_to_head"].isin([    "Self/Head", 
                                            "Wife/Husband", 
                                            "Son/Daughter-In-Law", 
                                            "Sister/Brother", 
                                            "Mother/Father", 
                                            "Brother/Sister-In-Law", 
                                            "Grandfather/Mother", 
                                            "Father/Mother-In-Law"]) &
                                        (merge["age"] >= 18)
    ]

    database.append(filtered)

df_database = pd.concat(database, ignore_index=True)

#CREATE PERSONAL IDENTIFIER 
df_database["personal_id"] = df_database["country"] + "_" + df_database["interview_key"].astype(str) + "_" + df_database["members_id"].astype(str)

#FINAL SORTING
df_database = df_database[['country', 'region', 'district', 'enumeration_area', 'personal_id', 'interview_key', 'relation_to_head', 'gender', 'age', 'years_of_schooling', 'education_level']] \
                .query("country != 'YES+A112:L126+A112:C126'")

[Botswana_identifying_info.csv] Missing columns: ['ea', 'region']
[Namibia_identifying_info.csv] Missing columns: ['dist']

## 2. Features

### 2.1 Creating HH-Level Features

In [ ]:
hh_features = []

for country, base_path in COUNTRIES.items():
    #ONE OBSERVATION PER HH
    # land_ownership          = data_cleaning.load_and_preprocess(base_path, f"{country}_land_ownership_and_access.csv",         features.LAND_OWNERSHIP_ACCESS_2023)
    # land_ownership          = data_cleaning.convert_land_sizes_to_acres(land_ownership, country, "land_measurement", mappings.acres_conversion_factors)
    # crop_expenditure        = data_cleaning.load_and_preprocess(base_path, f"{country}_expenditure_on_crops.csv",              features.CROP_EXPENDITURE_2023)
    # lifestock_grazing       = data_cleaning.load_and_preprocess(base_path, f"{country}_grazing_patterns_and_schemes.csv",      features.LIFESTOCK_GRAZING_2023)
    # livestock_income        = data_cleaning.load_and_preprocess(base_path, f"{country}_income_livestock.csv",                  features.LIFESTOCK_INCOME_2023)
    # livestock_expenditure   = data_cleaning.load_and_preprocess(base_path, f"{country}_expenditure_livestock.csv",             features.LIFESTOCK_EXPENDITURE_2023)
    # housing_conditions      = data_cleaning.load_and_preprocess(base_path, f"{country}_housing_conditions.csv",                features.HOUSING_CONDITIONS_2023)
    # energy_access           = data_cleaning.load_and_preprocess(base_path, f"{country}_access_to_energy.csv",                  features.ENERGY_ACCESS_2023)
    # internet_access         = data_cleaning.load_and_preprocess(base_path, f"{country}_internet_access.csv",                   features.INTERNET_ACCESS_2023)
    # social_network          = data_cleaning.load_and_preprocess(base_path, f"{country}_other_household_social_network.csv",    features.SOCIAL_NETWORK_2023)
    # social_embeddedness     = data_cleaning.load_and_preprocess(base_path, f"{country}_social_embeddedness.csv",               features.SOCIAL_EMBEDDEDNESS_2023)
    # food_insecurity         = data_cleaning.load_and_preprocess(base_path, f"{country}_food_insecurity_experiance_scale.csv",  features.FOOD_INSECURITY_2023)
    # road_connectivity       = data_cleaning.load_and_preprocess(base_path, f"{country}_road_connectivity.csv",                 features.ROAD_CONNECTIVITY_2023)

    #MANY OBSERVATIONS PER HH
    # if country == "Tanzania":
    #     #Tanzania's market access data is stored in value_chains.csv.
    #     market_access         = data_cleaning.load_and_preprocess(base_path, f"{country}_vale_chains.csv",                      features.MARKET_ACCESS_2023)
    # else:
    #     market_access         = data_cleaning.load_and_preprocess(base_path, f"{country}_market_access.csv",                     features.MARKET_ACCESS_2023)
    # market_access             = data_cleaning.resolve_duplicates(market_access, key_col="interview_key", sort_col="crop_contract_crop_type", ascending=True)
    # market_access             = data_cleaning.add_missing_indicators(market_access, ["market_output_distance_in_km", "market_input_distance_in_km"], sentinel=99999, suffix='_missing')

    # crop_production           = data_cleaning.load_and_preprocess(base_path, f"{country}_crop_production.csv",                   features.CROP_PRODUCTION_2023)
    # crop_production           = data_cleaning.crop_production_manual_cleaning(crop_production, "interview_key")
    # livestock_ownership       = data_cleaning.load_and_preprocess(base_path, f"{country}_livestock_ownership.csv",               features.LIVESTOCK_OWNERSHIP_2023) #different animals
    # livestock_ownership       = data_cleaning.create_livestock_features(livestock_ownership)


    # assets_owned              = data_cleaning.load_and_preprocess(base_path, f"{country}_assets.csv",                            features.ASSETS_OWNED_2023)
    # assets_owned              = data_cleaning.create_asset_features(assets_owned)
    # assets_owned              = data_cleaning.calculate_revenue(assets_owned, "asset_number_owned", "asset_price_per_unit", "asset_value")
    # assets_owned              = data_cleaning.aggregate_by_hh(assets_owned, ["asset_type"])
    
    # other_income              = data_cleaning.load_and_preprocess(base_path, f"{country}_other_income.csv",                      features.OTHER_INCOME_SOURCES_2023)
    # other_income              = data_cleaning.create_other_income_features(other_income)

    shocks_and_coping       = data_cleaning.load_and_preprocess(base_path, f"{country}_shocks_and_coping.csv",                 features.SHOCKS_AND_COPING_2023)



    #SOME TABLES ARE NOT AVAILABLE FOR EACH COUNTRY: optional_merges solves this as it only merges available tables
    merges = [
        # (land_ownership,          ["interview_key"],     "outer"),
        # (crop_expenditure,        ["interview_key"],     "outer"),
        # (lifestock_grazing,       ["interview_key"],     "outer")
        # (livestock_income,        ["interview_key"],     "outer")
        # (livestock_expenditure,   ["interview_key"],     "outer")
        # (housing_conditions,      ["interview_key"],     "outer")
        # (energy_access,           ["interview_key"],     "outer")
        # (internet_access,         ["interview_key"],     "outer")
        # (social_network,          ["interview_key"],     "outer")
        # (social_embeddedness,     ["interview_key"],     "outer")
        # (food_insecurity,         ["interview_key"],     "outer")
        # (road_connectivity,       ["interview_key"],     "outer")
        # (market_access,           ["interview_key"],     "outer")
        # (crop_production,         ["interview_key"],     "outer")
        # (livestock_ownership,     ["interview_key"],     "outer")
        # (assets_owned,            ["interview_key"],     "outer")
        # (other_income,         ["interview_key"],     "outer")
        (shocks_and_coping,         ["interview_key"],     "outer")


    ]

    df_help = None

    for df, keys, how in merges:
        if df_help is None:
            df_help = df
        else:
            df_help = df_help.merge(df, on=keys, how=how)
                
    #Adding the country to the table for identification
    df_help.insert(0, "country", country)

    hh_features.append(df_help)

df_hh_features = pd.concat(hh_features, ignore_index=True)

In [74]:
missing_by_country = (
    df_hh_features
    .groupby('country')
    .apply(lambda g: g.isna().mean())
    .sort_index()
)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(missing_by_country)

C:\Users\localuser\AppData\Local\Temp\ipykernel_1904\763753577.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.isna().mean())

          country  interview_key  other_income_amount_yearly
country
Botswana      0.0            0.0                         0.0
Kenya         0.0            0.0                         0.0
Namibia       0.0            0.0                         0.0
Tanzania      0.0            0.0                         0.0
Zambia        0.0            0.0                         0.0

In [64]:
# df_hh_features["crop_contract"].value_counts()
blub = df_hh_features["shock_type_affected_last_12_months"].value_counts()
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(blub)

KeyError: 'shock_type_affected_last_12_months'

In [75]:
len(df_hh_features)

1594

In [76]:
df_hh_features["interview_key"].nunique()

1594

In [77]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_hh_features)

       country interview_key  other_income_amount_yearly
0     Botswana   00-01-02-02                1.300000e+03
1     Botswana   00-34-52-14                6.000000e+03
2     Botswana   01-08-40-07                1.800000e+04
3     Botswana   01-11-02-57                4.200000e+04
4     Botswana   02-07-42-94                4.000000e+02
5     Botswana   02-31-03-32                2.400000e+04
6     Botswana   02-55-85-64                1.680000e+04
7     Botswana   03-33-65-79                1.000000e+03
8     Botswana   03-38-35-14                2.400000e+03
9     Botswana   03-62-40-58                1.250000e+04
10    Botswana   03-81-35-88                4.000000e+03
11    Botswana   03-91-71-73                3.600000e+04
12    Botswana   04-04-14-28                1.800000e+04
13    Botswana   04-05-30-01                5.240000e+04
14    Botswana   04-26-72-23                7.200000e+03
15    Botswana   04-92-41-49                8.000000e+03
16    Botswana   05-01-06-84                1.000000e+04
17    Botswana   05-16-40-57                1.920000e+04
18    Botswana   05-30-74-26                1.800000e+04
19    Botswana   05-35-63-46                7.600000e+03
20    Botswana   05-74-99-19                1.080000e+04
21    Botswana   05-76-24-30                6.000000e+03
22    Botswana   05-90-60-44                1.000000e+03
23    Botswana   05-94-07-12                7.200000e+03
24    Botswana   06-31-05-26                2.000000e+04
25    Botswana   06-32-06-25                2.040000e+04
26    Botswana   06-55-62-53                5.160000e+04
27    Botswana   06-64-69-84                8.400000e+03
28    Botswana   07-52-39-57                6.000000e+03
29    Botswana   07-73-56-26                1.200000e+04
30    Botswana   08-18-22-01                1.200000e+04
31    Botswana   08-72-41-04                8.400000e+03
32    Botswana   08-84-58-33                1.800000e+04
33    Botswana   08-89-64-68                5.964000e+04
34    Botswana   09-31-11-33                1.912000e+04
35    Botswana   09-47-23-08                4.400000e+03
36    Botswana   09-72-08-00                8.000000e+02
37    Botswana   09-79-14-71                1.320000e+04
38    Botswana   10-43-22-87                2.000000e+03
39    Botswana   11-05-72-97                7.200000e+03
40    Botswana   11-13-66-94                8.000000e+02
41    Botswana   11-16-18-86                2.440000e+04
42    Botswana   11-65-24-94                1.560000e+04
43    Botswana   11-71-40-81                1.000000e+03
44    Botswana   11-82-86-61                1.200000e+04
45    Botswana   12-03-37-86                3.960000e+04
46    Botswana   12-61-67-91                1.200000e+04
47    Botswana   12-91-55-52                7.500000e+03
48    Botswana   13-26-76-47                1.200000e+04
49    Botswana   13-49-27-25                9.600000e+03
50    Botswana   14-08-31-40                8.760000e+03
51    Botswana   14-14-61-40                1.960000e+04
52    Botswana   14-31-43-40                1.800000e+04
53    Botswana   14-98-70-62                6.000000e+03
54    Botswana   15-09-86-52                1.600000e+03
55    Botswana   15-81-26-28                1.200000e+04
56    Botswana   16-65-54-37                3.600000e+04
57    Botswana   16-86-88-22                3.000000e+02
58    Botswana   16-99-02-10                2.000000e+02
59    Botswana   17-63-55-71                6.000000e+03
60    Botswana   17-89-78-78                1.680000e+04
61    Botswana   18-54-82-39                3.000000e+02
62    Botswana   18-63-27-64                1.200000e+04
63    Botswana   18-81-00-96                2.160000e+04
64    Botswana   19-03-38-46                1.320000e+04
65    Botswana   19-25-83-42                6.000000e+03
66    Botswana   19-42-84-15                2.800000e+03
67    Botswana   19-83-50-72                6.600000e+04
68    Botswana   20-35-14-07                1.200000e+03
69    Botswana   20-37-92-05                1.200000e+03
70    Botswana   20-52-90-88                8.400000e+04
71    Botswana   20-77-43-56                6.000000e+03
72    Botswana   21-07-91-22                9.300000e+03
73    Botswana   21-25-86-78                2.460000e+04
74    Botswana   22-02-04-35                5.430000e+04
75    Botswana   22-19-53-02                3.000000e+02
76    Botswana   22-59-76-95                1.200000e+03
77    Botswana   22-90-51-93                9.000000e+04
78    Botswana   23-54-03-81                3.300000e+03
79    Botswana   23-66-97-33                4.950000e+04
80    Botswana   23-98-05-49                2.400000e+04
81    Botswana   24-09-68-36                2.064000e+04
82    Botswana   24-47-59-03                6.000000e+03
83    Botswana   24-72-61-31                1.000000e+03
84    Botswana   25-00-79-64                3.000000e+02
85    Botswana   25-32-96-44                8.400000e+03
86    Botswana   25-36-49-99                8.000000e+03
87    Botswana   25-52-14-98                2.160000e+04
88    Botswana   25-90-09-86                1.908000e+04
89    Botswana   25-90-19-11                1.800000e+04
90    Botswana   25-90-81-61                7.200000e+03
91    Botswana   26-07-22-36                1.880000e+04
92    Botswana   26-16-19-49                1.464000e+04
93    Botswana   27-16-23-86                5.000000e+02
94    Botswana   27-19-89-21                1.464000e+04
95    Botswana   27-55-59-32                3.600000e+03
96    Botswana   28-12-52-92                2.064000e+04
97    Botswana   28-99-62-67                1.200000e+04
98    Botswana   29-79-23-67                8.400000e+04
99    Botswana   29-79-40-11                1.200000e+04
100   Botswana   30-09-94-93                3.300000e+04
101   Botswana   31-20-26-05                8.400000e+03
102   Botswana   31-42-54-99                4.500000e+03
103   Botswana   31-99-53-07                3.480000e+04
104   Botswana   32-51-19-72                4.000000e+02
105   Botswana   32-64-27-45                1.000000e+03
106   Botswana   32-72-73-42                3.340000e+04
107   Botswana   32-73-63-74                5.000000e+02
108   Botswana   32-83-01-09                8.400000e+03
109   Botswana   32-84-70-99                2.400000e+03
110   Botswana   33-37-06-20                1.440000e+04
111   Botswana   33-44-32-83                7.800000e+03
112   Botswana   33-94-27-06                3.800000e+04
113   Botswana   35-31-07-84                9.860000e+03
114   Botswana   36-42-18-14                3.600000e+04
115   Botswana   36-43-41-97                5.000000e+02
116   Botswana   36-91-85-86                1.300000e+04
117   Botswana   37-03-14-78                7.440000e+03
118   Botswana   37-39-15-65                3.000000e+04
119   Botswana   37-39-45-84                2.000000e+03
120   Botswana   38-33-66-67                4.200000e+03
121   Botswana   38-98-52-39                4.800000e+03
122   Botswana   39-14-69-76                8.760000e+03
123   Botswana   39-36-01-20                2.080000e+04
124   Botswana   39-65-48-99                1.440000e+04
125   Botswana   40-00-25-74                3.600000e+03
126   Botswana   40-16-04-38                6.600000e+03
127   Botswana   40-28-46-68                2.000000e+02
128   Botswana   40-29-00-57                7.200000e+03
129   Botswana   41-03-53-12                4.000000e+02
130   Botswana   41-50-66-96                6.000000e+03
131   Botswana   41-82-62-49                1.000000e+03
132   Botswana   42-32-41-18                6.840000e+04
133   Botswana   42-50-27-40                3.600000e+03
134   Botswana   42-79-46-81                4.800000e+03
135   Botswana   42-95-35-09                7.120000e+04
136   Botswana   43-00-27-37                2.400000e+03
137   Botswana   43-12-71-52                2.800000e+03
138   Botswana   43-14-97-16                1.000000e+03
139   Botswana   43-28-98-57                1.200000e+04
140   Botswana   45-07-09-59                3.600000e+03
141   Botswana   45-44-88-31                1.800000e+04
142   Botswana   45-71-57-97                3.600000e+04
143   Botswana   45-71-76-98                3.600000e+04
144   Botswana   45-83-41-38                3.600000e+03
145   Botswana   46-82-10-07                3.000000e+02
146   Botswana   46-89-61-94                7.000000e+02
147   Botswana   48-16-15-04                5.000000e+02
148   Botswana   48-22-87-49                2.660000e+04
149   Botswana   48-57-10-38                2.500000e+02
150   Botswana   48-80-48-31                8.760000e+03
151   Botswana   48-93-31-20                3.100000e+03
152   Botswana   49-34-25-75                1.240000e+04
153   Botswana   49-80-23-99                6.800000e+03
154   Botswana   49-90-63-33                2.260000e+04
155   Botswana   50-01-20-35                1.000000e+03
156   Botswana   51-25-36-09                1.152000e+05
157   Botswana   51-31-85-01                8.760000e+03
158   Botswana   51-45-88-78                1.400000e+03
159   Botswana   51-50-93-70                2.400000e+03
160   Botswana   51-67-29-73                5.000000e+02
161   Botswana   52-28-82-48                2.340000e+04
162   Botswana   52-46-02-95                1.560000e+04
163   Botswana   52-55-71-22                6.000000e+03
164   Botswana   52-70-09-40                8.000000e+02
165   Botswana   53-04-65-79                1.600000e+03
166   Botswana   53-23-37-57                4.800000e+03
167   Botswana   53-41-55-25                1.000000e+02
168   Botswana   53-81-28-44                1.880000e+04
169   Botswana   54-13-05-65                4.476000e+04
170   Botswana   54-48-29-54                1.000000e+04
171   Botswana   54-69-26-46                8.000000e+03
172   Botswana   55-27-15-85                1.200000e+05
173   Botswana   55-33-21-42                1.080000e+04
174   Botswana   55-35-77-06                6.390000e+04
175   Botswana   55-44-38-36                2.850000e+04
176   Botswana   56-53-54-49                3.136000e+05
177   Botswana   56-62-10-52                8.900000e+03
178   Botswana   57-12-45-97                1.800000e+04
179   Botswana   57-52-43-19                7.200000e+03
180   Botswana   58-42-18-32                6.600000e+03
181   Botswana   58-55-75-07                1.620000e+04
182   Botswana   58-76-16-53                1.800000e+04
183   Botswana   58-90-20-54                4.800000e+03
184   Botswana   59-08-91-97                1.500000e+04
185   Botswana   59-60-43-57                2.640000e+04
186   Botswana   59-63-12-34                3.600000e+04
187   Botswana   60-00-51-13                1.760000e+04
188   Botswana   60-10-68-48                7.200000e+04
189   Botswana   60-29-48-02                1.140000e+04
190   Botswana   60-57-49-31                8.760000e+03
191   Botswana   61-12-40-36                3.300000e+03
192   Botswana   61-17-81-33                4.000000e+03
193   Botswana   61-20-94-35                1.800000e+04
194   Botswana   61-35-56-51                1.000000e+03
195   Botswana   61-84-77-75                6.000000e+03
196   Botswana   62-23-61-37                2.400000e+04
197   Botswana   62-46-14-70                2.000000e+02
198   Botswana   62-49-02-44                1.560000e+04
199   Botswana   63-11-78-96                7.200000e+03
200   Botswana   64-05-81-04                1.460000e+04
201   Botswana   64-91-38-41                1.260000e+05
202   Botswana   65-23-07-01                1.500000e+03
203   Botswana   65-38-87-54                1.500000e+03
204   Botswana   65-48-87-48                2.280000e+04
205   Botswana   65-67-13-71                6.000000e+03
206   Botswana   67-07-39-08                2.640000e+04
207   Botswana   67-12-10-28                8.400000e+03
208   Botswana   67-95-64-84                1.920000e+04
209   Botswana   68-12-26-88                2.000000e+03
210   Botswana   68-17-57-15                1.800000e+04
211   Botswana   68-84-82-12                8.200000e+03
212   Botswana   69-29-47-18                5.000000e+02
213   Botswana   69-53-29-77                8.000000e+02
214   Botswana   69-84-94-36                6.000000e+02
215   Botswana   70-67-46-48                1.200000e+05
216   Botswana   71-09-05-63                7.200000e+03
217   Botswana   71-10-70-44                3.720000e+04
218   Botswana   71-23-95-90                8.000000e+02
219   Botswana   71-64-26-40                1.920000e+04
220   Botswana   71-80-89-34                4.300000e+03
221   Botswana   72-36-49-36                1.680000e+04
222   Botswana   72-37-57-39                2.000000e+02
223   Botswana   72-66-07-18                9.000000e+04
224   Botswana   72-80-69-88                3.600000e+03
225   Botswana   72-84-79-72                8.400000e+04
226   Botswana   73-36-17-40                1.320000e+04
227   Botswana   73-70-95-80                3.600000e+03
228   Botswana   74-08-40-24                1.440000e+04
229   Botswana   74-79-87-37                1.560000e+04
230   Botswana   75-18-13-88                1.680000e+04
231   Botswana   75-53-97-04                7.200000e+03
232   Botswana   75-58-44-85                1.500000e+03
233   Botswana   76-02-43-67                5.600000e+02
234   Botswana   76-02-50-71                6.000000e+03
235   Botswana   76-65-29-85                2.280000e+04
236   Botswana   77-34-61-84                8.760000e+03
237   Botswana   77-62-89-56                7.200000e+03
238   Botswana   78-32-31-52                5.800000e+04
239   Botswana   79-05-50-27                1.000000e+03
240   Botswana   79-24-47-25                1.600000e+03
241   Botswana   79-30-25-19                6.000000e+02
242   Botswana   79-48-70-94                2.076000e+04
243   Botswana   80-21-91-02                8.760000e+03
244   Botswana   80-35-75-14                7.200000e+04
245   Botswana   80-48-57-31                8.000000e+03
246   Botswana   80-53-41-39                1.200000e+04
247   Botswana   80-76-98-64                2.900000e+03
248   Botswana   80-79-44-48                9.000000e+02
249   Botswana   81-05-32-56                2.300000e+03
250   Botswana   81-06-64-01                7.030000e+03
251   Botswana   81-24-00-67                5.000000e+02
252   Botswana   81-28-91-79                1.000000e+03
253   Botswana   81-33-83-30                8.760000e+03
254   Botswana   82-85-64-69                2.000000e+04
255   Botswana   83-85-13-86                1.200000e+04
256   Botswana   84-33-06-87                2.850000e+04
257   Botswana   84-66-38-33                4.800000e+03
258   Botswana   84-73-72-31                7.800000e+03
259   Botswana   84-90-94-70                2.400000e+04
260   Botswana   85-23-91-16                2.500000e+03
261   Botswana   85-30-41-56                1.200000e+04
262   Botswana   85-34-28-65                7.200000e+03
263   Botswana   85-43-95-57                4.800000e+04
264   Botswana   85-49-52-94                1.200000e+04
265   Botswana   85-54-41-38                8.400000e+03
266   Botswana   86-00-77-05                6.311000e+04
267   Botswana   86-01-74-97                1.416000e+05
268   Botswana   86-10-11-11                1.200000e+03
269   Botswana   86-16-04-54                3.883176e+04
270   Botswana   86-28-43-28                3.960000e+04
271   Botswana   86-55-30-87                2.000000e+03
272   Botswana   87-13-21-98                3.000000e+04
273   Botswana   87-22-49-94                2.000000e+02
274   Botswana   87-31-98-00                6.170000e+02
275   Botswana   87-48-42-67                1.200000e+04
276   Botswana   87-65-62-49                5.000000e+02
277   Botswana   87-80-21-51                1.560000e+04
278   Botswana   88-01-88-32                4.920000e+04
279   Botswana   88-51-36-66                4.800000e+03
280   Botswana   89-51-80-40                2.400000e+03
281   Botswana   89-88-34-15                3.800000e+04
282   Botswana   90-03-82-22                7.200000e+03
283   Botswana   90-62-42-39                1.200000e+04
284   Botswana   91-02-01-07                2.000000e+03
285   Botswana   91-35-74-95                9.600000e+03
286   Botswana   91-79-46-21                1.000000e+04
287   Botswana   91-91-62-09                8.000000e+02
288   Botswana   92-09-46-86                1.000000e+03
289   Botswana   92-23-96-13                2.400000e+04
290   Botswana   92-30-60-06                1.020000e+04
291   Botswana   92-48-70-16                1.000000e+03
292   Botswana   92-49-74-52                1.980000e+04
293   Botswana   93-40-82-23                3.736000e+04
294   Botswana   93-42-86-13                1.320000e+04
295   Botswana   93-61-95-87                5.200000e+03
296   Botswana   93-71-48-41                4.000000e+01
297   Botswana   93-79-44-00                1.200000e+04
298   Botswana   94-16-94-83                6.000000e+03
299   Botswana   94-29-79-85                6.000000e+03
300   Botswana   94-41-84-42                1.120000e+04
301   Botswana   94-77-43-36                3.390000e+04
302   Botswana   94-91-03-07                4.776000e+04
303   Botswana   95-19-87-73                1.440000e+04
304   Botswana   95-39-93-93                3.000000e+03
305   Botswana   95-51-95-92                2.050000e+04
306   Botswana   95-74-95-07                8.400000e+03
307   Botswana   96-34-22-21                1.500000e+03
308   Botswana   96-39-11-89                6.000000e+03
309   Botswana   97-60-60-10                3.000000e+04
310   Botswana   97-63-44-51                1.000000e+04
311   Botswana   98-31-37-04                1.200000e+04
312   Botswana   98-37-88-19                3.000000e+02
313   Botswana   98-74-77-48                7.200000e+03
314   Botswana   98-85-46-77                1.560000e+04
315   Botswana   98-98-98-22                6.000000e+03
316   Botswana   99-40-82-80                3.000000e+04
317      Kenya   00-68-70-04                2.600000e+05
318      Kenya   01-28-41-84                8.000000e+03
319      Kenya   01-51-99-07                7.000000e+03
320      Kenya   01-54-87-19                1.250000e+05
321      Kenya   02-67-98-73                6.000000e+05
322      Kenya   02-78-83-36                2.400000e+04
323      Kenya   03-69-84-05                1.800000e+04
324      Kenya   04-02-73-28                1.100000e+05
325      Kenya   04-31-65-65                3.600000e+05
326      Kenya   04-52-21-75                5.000000e+03
327      Kenya   05-33-62-23                2.000000e+04
328      Kenya   05-86-89-30                9.600000e+04
329      Kenya   07-91-23-12                3.200000e+04
330      Kenya   08-76-57-31                2.400000e+04
331      Kenya   08-94-02-07                1.420000e+05
332      Kenya   09-02-42-42                6.080400e+04
333      Kenya   09-54-26-75                2.400000e+04
334      Kenya   09-64-46-58                5.000000e+04
335      Kenya   09-89-86-48                6.000000e+04
336      Kenya   10-18-23-80                5.000000e+03
337      Kenya   10-60-87-78                7.800000e+05
338      Kenya   10-69-61-22                2.400000e+03
339      Kenya   10-78-86-05                4.400000e+05
340      Kenya   11-10-12-08                6.000000e+04
341      Kenya   12-04-44-96                4.400000e+05
342      Kenya   12-15-65-08                2.026800e+04
343      Kenya   13-37-47-48                8.000000e+04
344      Kenya   13-38-59-03                2.000000e+03
345      Kenya   13-52-61-75                1.100000e+05
346      Kenya   14-71-87-39                6.000000e+03
347      Kenya   15-84-79-29                3.200000e+04
348      Kenya   16-40-92-10                3.200000e+04

### 2.2 Creating Individual-Level Features

In [62]:
individual_features = []

for country, base_path in COUNTRIES.items():
    #NO CLEANING NECESSARY 

    #CLEANING NECESSARY


    #SOME FEATURES ARE NOT AVAILABLE FOR EACH COUNTRY: optional_merges solves this as it only merges available features
    optional_merges = [
    ]

    df_help = None

    for df, keys, how in optional_merges:
        if df is not None:
            if df_help is None:
                df_help = df
            else:
                df_help = df_help.merge(df, on=keys, how=how)

    individual_features.append(df_help)

df_individual_features = pd.concat(individual_features, ignore_index=True)

ValueError: All objects passed were None

## 3. Write clean data to data/raw folder

In [ ]:
df.to_csv(config.PROCESSED_DATA_DIR / "clean_data.csv", index=False)