# Data Cleaning 

This notebook cleans the raw data available in data/raw and writes the clean version back to the folder data/processed.

In [176]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np 
from c08_farming_exit import config, features, data_cleaning, mappings

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [54]:
# #In case you want to run Stata in a cell using the magic command %%stata, initialize it first!
# from c08_farming_exit.stata_utils import init_stata
# init_stata()

In [113]:
COUNTRIES = {
    "Botswana": config.RAW_DATA_DIR / "Botswana",
    "Kenya":    config.RAW_DATA_DIR / "Kenya",
    "Namibia":  config.RAW_DATA_DIR / "Namibia",
    "Tanzania": config.RAW_DATA_DIR / "Tanzania",
    "Zambia":   config.RAW_DATA_DIR / "Zambia",
}

## 1. Database

In [112]:
#THE DATABASE CONSISTS OF ADULTS ONLY
database = []

for country, base_path in COUNTRIES.items():
    identifying_info    = data_cleaning.load_and_preprocess(base_path, f"{country}_identifying_info.csv",                  features.IDENTIFYING_INFO_2023)
    
    hh_members          = data_cleaning.load_and_preprocess(base_path, f"{country}_household_members_characterstics.csv",  features.HH_MEMBERS_2023)
    hh_members          = data_cleaning.add_years_of_schooling(hh_members, mappings.education_mapping)

    merge = identifying_info.merge(hh_members, on=["interview_key"], how="inner")
    
    filtered = merge[
        merge["relation_to_head"].isin([    "Self/Head", 
                                            "Wife/Husband", 
                                            "Son/Daughter-In-Law", 
                                            "Sister/Brother", 
                                            "Mother/Father", 
                                            "Brother/Sister-In-Law", 
                                            "Grandfather/Mother", 
                                            "Father/Mother-In-Law"]) &
                                        (merge["age"] >= 18)
    ]

    database.append(filtered)

df_database = pd.concat(database, ignore_index=True)

#CREATE PERSONAL IDENTIFIER 
df_database["personal_id"] = df_database["country"] + "_" + df_database["interview_key"].astype(str) + "_" + df_database["members_id"].astype(str)

#FINAL SORTING
df_database = df_database[['country', 'region', 'district', 'enumeration_area', 'personal_id', 'interview_key', 'relation_to_head', 'gender', 'age', 'years_of_schooling', 'education_level']] \
                .query("country != 'YES+A112:L126+A112:C126'")

[Botswana_identifying_info.csv] Missing columns: ['ea', 'region']
[Namibia_identifying_info.csv] Missing columns: ['dist']

## 2. Features

### 2.1 Creating HH-Level Features

In [177]:
hh_features = []

for country, base_path in COUNTRIES.items():
    #NO CLEANING NECESSARY - one observation per hh
    # land_ownership          = data_cleaning.load_and_preprocess(base_path, f"{country}_land_ownership_and_access.csv",         features.LAND_OWNERSHIP_ACCESS_2023)
    # land_ownership          = data_cleaning.convert_land_sizes_to_acres(land_ownership, country)
    # crop_expenditure        = data_cleaning.load_and_preprocess(base_path, f"{country}_expenditure_on_crops.csv",              features.CROP_EXPENDITURE_2023)
    # lifestock_grazing       = data_cleaning.load_and_preprocess(base_path, f"{country}_grazing_patterns_and_schemes.csv",      features.LIFESTOCK_GRAZING_2023)
    # livestock_income        = data_cleaning.load_and_preprocess(base_path, f"{country}_income_livestock.csv",                  features.LIFESTOCK_INCOME_2023)
    # livestock_expenditure   = data_cleaning.load_and_preprocess(base_path, f"{country}_expenditure_livestock.csv",             features.LIFESTOCK_EXPENDITURE_2023)
    # housing_conditions      = data_cleaning.load_and_preprocess(base_path, f"{country}_housing_conditions.csv",                features.HOUSING_CONDITIONS_2023)
    # energy_access           = data_cleaning.load_and_preprocess(base_path, f"{country}_access_to_energy.csv",                  features.ENERGY_ACCESS_2023)
    # internet_access         = data_cleaning.load_and_preprocess(base_path, f"{country}_internet_access.csv",                   features.INTERNET_ACCESS_2023)
    # social_network          = data_cleaning.load_and_preprocess(base_path, f"{country}_other_household_social_network.csv",    features.SOCIAL_NETWORK_2023)
    # social_embeddedness     = data_cleaning.load_and_preprocess(base_path, f"{country}_social_embeddedness.csv",               features.SOCIAL_EMBEDDEDNESS_2023)
    # food_insecurity         = data_cleaning.load_and_preprocess(base_path, f"{country}_food_insecurity_experiance_scale.csv",  features.FOOD_INSECURITY_2023)
    # road_connectivity       = data_cleaning.load_and_preprocess(base_path, f"{country}_road_connectivity.csv",                 features.ROAD_CONNECTIVITY_2023)

    # #CLEANING NECESSARY - many observations per hh
    # market_access           = data_cleaning.load_and_preprocess(base_path, f"{country}_market_access.csv",                     features.MARKET_ACCESS_2023)
    # #market data is missing for Tanzania!
    # if market_access is None:
    #     print(f"  -> missing market_access file for {country}")
    #     continue
    # market_access           = data_cleaning.resolve_duplicates(market_access, key_col="interview_key", sort_col="crop_contract_crop_type", ascending=True)
    # market_access           = data_cleaning.add_missing_indicators(market_access, ["market_output_distance_in_km", "market_input_distance_in_km"], sentinel=99999, suffix='_missing')
    crop_production         = data_cleaning.load_and_preprocess(base_path, f"{country}_crop_production.csv",                   features.CROP_PRODUCTION_2023) #different crops
    # livestock_ownership     = data_cleaning.load_and_preprocess(base_path, f"{country}_livestock_ownership.csv",               features.LIVESTOCK_OWNERSHIP_2023) #different animals
    # assets_owned            = data_cleaning.load_and_preprocess(base_path, f"{country}_assets.csv",                            features.ASSETS_OWNED_2023)
    # shocks_and_coping       = data_cleaning.load_and_preprocess(base_path, f"{country}_shocks_and_coping.csv",                 features.SHOCKS_AND_COPING_2023)
    # other_income            = data_cleaning.load_and_preprocess(base_path, f"{country}_other_income.csv",                      features.OTHER_INCOME_SOURCES_2023)


    #SOME TABLES ARE NOT AVAILABLE FOR EACH COUNTRY: optional_merges solves this as it only merges available tables
    optional_merges = [
        # (land_ownership,          ["interview_key"],     "outer"),
        # (crop_expenditure,        ["interview_key"],     "outer"),
        # (lifestock_grazing,       ["interview_key"],     "outer")
        # (livestock_income,        ["interview_key"],     "outer")
        # (livestock_expenditure,   ["interview_key"],     "outer")
        # (housing_conditions,      ["interview_key"],     "outer")
        # (energy_access,           ["interview_key"],     "outer")
        # (internet_access,         ["interview_key"],     "outer")
        # (social_network,          ["interview_key"],     "outer")
        # (social_embeddedness,     ["interview_key"],     "outer")
        # (food_insecurity,         ["interview_key"],     "outer")
        # (road_connectivity,       ["interview_key"],     "outer")
        # (market_access,           ["interview_key"],     "outer")
        (crop_production,    ["interview_key"],     "outer")


    ]

    df_help = None

    for df, keys, how in optional_merges:
        if df is not None:
            if df_help is None:
                df_help = df
            else:
                df_help = df_help.merge(df, on=keys, how=how)
                
    if df_help is not None:            
        #Adding the country to the table for identification
        df_help.insert(0, "country", country)

    hh_features.append(df_help)


df_hh_features = pd.concat(hh_features, ignore_index=True)

In [178]:
missing_by_country = (
    df_hh_features
    .groupby('country')
    .apply(lambda g: g.isna().mean())
    .sort_index()
)
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(missing_by_country)

C:\Users\localuser\AppData\Local\Temp\ipykernel_16092\763753577.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.isna().mean())

,country,interview_key,crop_type,crop_harvested,crop_output,crop_unit,crop_sale,crop_sale_amount,crop_sale_unit,crop_sale_price_per_unit,crop_buyer_market,crop_buyer_trader,crop_buyer_cooperative,crop_buyer_commercial_farm,crop_buyer_hospitality,crop_buyer_government,crop_home_consumption,crop_home_consumption_unit,crop_storage,crop_storage_amount,crop_storage_unit,crop_organic_fertilizer,crop_inorganic_fertilizer,crop_pesticides,crop_tractor
country,,,,,,,,,,,,,,,,,,,,,,,,,
Botswana,0.0,0.0,0.0,0.0,0.615702,0.619835,0.619835,0.925620,0.925620,0.925620,0.929752,0.925620,0.925620,0.925620,0.925620,0.925620,0.619835,0.657025,0.0,0.880165,0.880165,0.049587,0.049587,0.049587,0.049587
Kenya,0.0,0.0,0.0,0.0,0.712305,0.714038,0.714038,0.837088,0.838821,0.838821,0.842288,0.844021,0.840555,0.838821,0.840555,0.838821,0.714038,0.741768,0.0,0.911612,0.911612,0.000000,0.000000,0.000000,0.000000
Namibia,0.0,0.0,0.0,0.0,0.398361,0.429508,0.429508,0.914754,0.914754,0.914754,0.916393,0.914754,0.916393,0.914754,0.914754,0.914754,0.429508,0.595082,0.0,0.640984,0.645902,0.027869,0.027869,0.027869,0.027869
Tanzania,0.0,0.0,0.0,0.0,0.174949,0.186521,0.186521,0.608577,0.617427,0.617427,0.622873,0.625596,0.617427,0.617427,0.617427,0.617427,0.186521,0.335602,0.0,0.513955,0.520762,0.002042,0.002042,0.002042,0.002042
Zambia,0.0,0.0,0.0,0.0,0.339400,0.370450,0.370450,0.936831,0.937901,0.937901,0.937901,0.941113,0.937901,0.937901,0.938972,0.937901,0.370450,0.432548,0.0,0.516060,0.521413,0.011777,0.011777,0.011777,0.011777

In [183]:
# df_hh_features["crop_contract"].value_counts()
df_hh_features.groupby("country")["crop_unit"].value_counts()

country   crop_unit
Botswana  50 kg bag        29
          Numbers          16
          Kilograms        12
          10kg bag          6
          Bale / Bundle     6
                           ..
Zambia    Basins            4
          Crates            2
          Bunches           1
          Grams             1
          Liters            1
Name: count, Length: 67, dtype: int64

In [182]:
with pd.option_context('display.max_rows', None, 'display.max_columns', None):
    display(df_hh_features[df_hh_features["country"]=="Botswana"])

,country,interview_key,crop_type,crop_harvested,crop_output,crop_unit,crop_sale,crop_sale_amount,crop_sale_unit,crop_sale_price_per_unit,crop_buyer_market,crop_buyer_trader,crop_buyer_cooperative,crop_buyer_commercial_farm,crop_buyer_hospitality,crop_buyer_government,crop_home_consumption,crop_home_consumption_unit,crop_storage,crop_storage_amount,crop_storage_unit,crop_organic_fertilizer,crop_inorganic_fertilizer,crop_pesticides,crop_tractor
0,Botswana,95-91-52-45,MAIZE,Yes,25.0,10kg bag,Yes,20.00,10kg bag,80.0,No,No,Yes,No,No,No,5.0,10kg bag,No,NaN,NaN,No,Yes,Yes,No
1,Botswana,95-91-52-45,MILLET/MAIWA,Yes,25.0,10kg bag,Yes,20.00,10kg bag,80.0,No,No,Yes,No,No,No,5.0,10kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN
2,Botswana,93-61-95-87,ONION,Yes,2.5,2kg packet,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2kg packet,No,NaN,NaN,Yes,No,No,No
3,Botswana,93-61-95-87,IRISH POTATO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
4,Botswana,93-61-95-87,PUMPKIN,Yes,5.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Kilograms,No,NaN,NaN,Yes,No,No,No
5,Botswana,93-61-95-87,CHILLI PEPPER (SHOMBO),Yes,500.0,Grams,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500.0,Grams,No,NaN,NaN,Yes,No,No,No
6,Botswana,71-09-05-63,GUAVA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
7,Botswana,71-09-05-63,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
8,Botswana,81-05-32-56,BEANS/COWPEA,Yes,20.0,Liters,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Liters,Yes,0.5,Other (please specify),NaN,NaN,NaN,NaN
9,Botswana,81-05-32-56,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
10,Botswana,81-05-32-56,GREEN VEGETABLE,Yes,50.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN
11,Botswana,85-23-91-16,MAIZE,Yes,10.0,10kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,10kg bag,Yes,6.0,10kg bag,Yes,No,No,Yes
12,Botswana,53-06-23-41,MAIZE,Yes,15.0,50 kg bag,Yes,5000.00,50 kg bag,350.0,Yes,No,No,No,No,No,1.0,50 kg bag,Yes,5.0,50 kg bag,No,No,No,Yes
13,Botswana,53-06-23-41,SUGAR CANE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
14,Botswana,53-06-23-41,SORGHUM,Yes,3.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,50 kg bag,Yes,1.0,50 kg bag,No,No,No,No
15,Botswana,68-84-82-12,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
16,Botswana,68-84-82-12,MILLET/MAIWA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
17,Botswana,68-84-82-12,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
18,Botswana,42-95-35-09,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
19,Botswana,42-95-35-09,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
20,Botswana,42-95-35-09,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
21,Botswana,92-23-96-13,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
22,Botswana,22-90-51-93,MAIZE,Yes,3.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,50 kg bag,Yes,1.0,50 kg bag,No,Yes,No,Yes
23,Botswana,22-90-51-93,MILLET/MAIWA,Yes,9.0,50 kg bag,Yes,4.00,50 kg bag,400.0,Yes,No,No,No,No,No,2.0,50 kg bag,Yes,3.0,50 kg bag,No,Yes,No,Yes
24,Botswana,22-90-51-93,SORGHUM,Yes,2.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes,2.0,50 kg bag,No,Yes,No,Yes
25,Botswana,33-37-06-20,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
26,Botswana,33-37-06-20,PAWPAW,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
27,Botswana,62-05-75-13,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
28,Botswana,62-05-75-13,SORGHUM,Yes,2.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,50 kg bag,No,NaN,NaN,No,No,No,No
29,Botswana,12-03-37-86,ONION,Yes,5.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Kilograms,No,NaN,NaN,Yes,No,Yes,No
30,Botswana,12-03-37-86,GREEN VEGETABLE,Yes,5.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Kilograms,No,NaN,NaN,Yes,No,Yes,No
31,Botswana,12-03-37-86,TOMATO,Yes,8.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,Kilograms,No,NaN,NaN,Yes,No,Yes,No
32,Botswana,07-73-56-26,MAIZE,Yes,7.0,25kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,25kg bag,Yes,4.0,25kg bag,No,Yes,No,Yes
33,Botswana,07-73-56-26,MELON/EGUSI,Yes,3.0,Wheelbarrow,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Wheelbarrow,No,NaN,NaN,No,Yes,No,Yes
34,Botswana,07-73-56-26,OTHER(SPECIFY),Yes,4.0,Other (please specify),No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,Other (please specify),No,NaN,NaN,No,Yes,No,Yes
35,Botswana,81-06-64-01,OTHER SPECIFY,Yes,20.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,Numbers,No,NaN,NaN,No,No,No,No
36,Botswana,81-06-64-01,MAIZE,Yes,10.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,Kilograms,No,NaN,NaN,No,No,No,No
37,Botswana,17-96-77-43,BEANS/COWPEA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
38,Botswana,17-96-77-43,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
39,Botswana,17-96-77-43,MILLET/MAIWA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
40,Botswana,17-96-77-43,GARLIC,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
41,Botswana,17-96-77-43,ONION,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
42,Botswana,17-96-77-43,GREEN VEGETABLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,No
43,Botswana,17-96-77-43,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,250000.0,Liters,No,Yes,Yes,Yes
44,Botswana,11-82-86-61,MAIZE,Yes,300.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0,Numbers,No,NaN,NaN,No,No,No,Yes
45,Botswana,03-50-12-90,BEANS/COWPEA,Yes,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,Yes,Yes
46,Botswana,81-28-91-79,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
47,Botswana,07-52-39-57,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
48,Botswana,07-52-39-57,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
49,Botswana,94-41-84-42,SORGHUM,Yes,10.0,50 kg bag,Yes,6.00,50 kg bag,200.0,Yes,No,No,No,No,No,4.0,50 kg bag,No,NaN,NaN,No,No,No,Yes
50,Botswana,57-12-45-97,LEMON,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
51,Botswana,57-12-45-97,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
52,Botswana,57-12-45-97,AVOCADO PEAR,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
53,Botswana,51-25-36-09,BEANS/COWPEA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
54,Botswana,51-25-36-09,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
55,Botswana,52-46-02-95,MAIZE,Yes,1.0,25kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,25kg bag,No,NaN,NaN,No,No,No,No
56,Botswana,52-46-02-95,MELON/EGUSI,Yes,13.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,Numbers,No,NaN,NaN,No,No,No,No
57,Botswana,07-52-31-91,APPLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
58,Botswana,07-52-31-91,GUAVA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
59,Botswana,07-52-31-91,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
60,Botswana,67-07-39-08,MILLET/MAIWA,Yes,5.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,50 kg bag,Yes,3.0,50 kg bag,No,No,No,No
61,Botswana,67-07-39-08,SORGHUM,Yes,5.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes,3.0,50 kg bag,No,No,No,No
62,Botswana,27-20-78-36,OTHER SPECIFY,Yes,2.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Numbers,No,NaN,NaN,No,No,No,No
63,Botswana,27-20-78-36,BEANS/COWPEA,Yes,6.0,2kg packet,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2kg packet,Yes,2.0,2kg packet,Yes,No,Yes,No
64,Botswana,27-20-78-36,GROUND NUT/PEANUTS,Yes,5.0,Kilograms,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,Kilograms,No,NaN,NaN,No,No,No,No
65,Botswana,84-90-94-70,OTHER SPECIFY,Yes,5.0,Bale / Bundle,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Bale / Bundle,No,NaN,NaN,No,Yes,No,No
66,Botswana,84-90-94-70,GREEN VEGETABLE,Yes,4.0,Bale / Bundle,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,Bale / Bundle,No,NaN,NaN,No,Yes,No,No
67,Botswana,03-79-50-93,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,Yes,No
68,Botswana,03-79-50-93,TOMATO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,Yes,No
69,Botswana,03-79-50-93,SORGHUM,Yes,40.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,50 kg bag,No,NaN,NaN,No,No,Yes,Yes
70,Botswana,55-35-77-06,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
71,Botswana,55-35-77-06,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
72,Botswana,55-35-77-06,MELON/EGUSI,Yes,500.0,Other (please specify),Yes,500.00,Other (please specify),20.0,Yes,No,No,No,No,No,50.0,Other (please specify),No,NaN,NaN,No,No,No,Yes
73,Botswana,44-69-61-71,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
74,Botswana,44-69-61-71,OKRO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
75,Botswana,44-69-61-71,GREEN VEGETABLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
76,Botswana,33-94-27-06,BEANS/COWPEA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
77,Botswana,33-94-27-06,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
78,Botswana,33-94-27-06,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
79,Botswana,87-31-98-00,GREEN VEGETABLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
80,Botswana,15-39-44-44,BEANS/COWPEA,Yes,94.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,No,NaN,NaN,Yes,No,Yes,Yes
81,Botswana,57-32-99-06,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,Yes,Yes
82,Botswana,82-76-66-89,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
83,Botswana,56-62-79-46,GUAVA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
84,Botswana,56-62-79-46,LEMON,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
85,Botswana,56-62-79-46,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
86,Botswana,56-62-79-46,PAWPAW,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
87,Botswana,56-62-79-46,BANANA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
88,Botswana,38-98-52-39,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
89,Botswana,38-98-52-39,ONION,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
90,Botswana,38-98-52-39,GREEN VEGETABLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
91,Botswana,38-98-52-39,TOMATO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
92,Botswana,94-29-79-85,BEANS/COWPEA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
93,Botswana,94-29-79-85,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
94,Botswana,13-97-69-06,MAIZE,Yes,4.0,50 kg bag,Yes,3.00,50 kg bag,200.0,Yes,No,No,No,No,No,1.0,25kg bag,Yes,1.0,25kg bag,No,No,No,Yes
95,Botswana,81-33-83-30,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
96,Botswana,81-33-83-30,MAIZE,Yes,5.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,50 kg bag,No,NaN,NaN,No,No,No,Yes
97,Botswana,31-99-53-07,BEANS/COWPEA,Yes,3.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,50 kg bag,Yes,1.0,50 kg bag,No,No,No,No
98,Botswana,31-99-53-07,MAIZE,Yes,2.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,50 kg bag,No,NaN,NaN,No,No,No,No
99,Botswana,31-99-53-07,MELON/EGUSI,Yes,30.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Numbers,No,NaN,NaN,No,No,No,No
100,Botswana,31-99-53-07,MILLET/MAIWA,Yes,3.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,50 kg bag,Yes,2.0,50 kg bag,No,No,No,No
101,Botswana,31-99-53-07,BANANA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
102,Botswana,31-99-53-07,SORGHUM,Yes,2.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,50 kg bag,No,NaN,NaN,No,No,No,No
103,Botswana,22-18-88-41,TOMATO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN
104,Botswana,09-79-14-71,PUMPKIN,Yes,200.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes,200.0,Numbers,No,No,No,Yes
105,Botswana,09-79-14-71,SORGHUM,Yes,9.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,50 kg bag,Yes,9.0,50 kg bag,No,No,No,Yes
106,Botswana,71-80-89-34,MAIZE,Yes,250.0,Numbers,Yes,200.00,Numbers,10.0,Yes,No,No,No,No,No,25.0,Numbers,No,NaN,NaN,Yes,No,Yes,No
107,Botswana,71-80-89-34,CHILLI PEPPER (SHOMBO),No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,Yes,No
108,Botswana,71-80-89-34,GUAVA,Yes,150.0,Numbers,Yes,120.00,Numbers,2.0,Yes,No,No,No,No,No,30.0,Numbers,No,NaN,NaN,Yes,No,Yes,No
109,Botswana,71-80-89-34,LEMON,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
110,Botswana,71-80-89-34,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,Yes,No
111,Botswana,71-80-89-34,PAWPAW,Yes,13.0,Numbers,Yes,13.00,Numbers,30.0,Yes,No,No,No,No,No,0.0,NaN,No,NaN,NaN,Yes,No,Yes,No
112,Botswana,55-44-38-36,OTHER SPECIFY,Yes,2.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,50 kg bag,No,NaN,NaN,Yes,No,No,No
113,Botswana,55-44-38-36,GUAVA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
114,Botswana,55-44-38-36,LEMON,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
115,Botswana,55-44-38-36,MANGO,Yes,1.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,50 kg bag,No,NaN,NaN,Yes,No,No,No
116,Botswana,55-44-38-36,OTHER(SPECIFY),No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
117,Botswana,55-44-38-36,BANANA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
118,Botswana,55-44-38-36,PINEAPPLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
119,Botswana,92-09-46-86,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
120,Botswana,40-16-04-38,BEANS/COWPEA,Yes,2.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,25kg bag,Yes,2.0,50 kg bag,No,No,No,Yes
121,Botswana,88-23-45-95,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
122,Botswana,88-23-45-95,ONION,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
123,Botswana,88-23-45-95,GREEN VEGETABLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
124,Botswana,88-23-45-95,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
125,Botswana,88-23-45-95,PAWPAW,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
126,Botswana,53-04-65-79,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
127,Botswana,08-72-41-04,MAIZE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
128,Botswana,08-72-41-04,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,Yes
129,Botswana,48-20-18-94,MAIZE,Yes,10.0,50 kg bag,Yes,5.00,50 kg bag,3.8,No,No,Yes,No,No,No,3.0,50 kg bag,Yes,1.0,50 kg bag,No,Yes,No,Yes
130,Botswana,48-20-18-94,SORGHUM,Yes,10.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,Yes,10.0,50 kg bag,No,Yes,No,Yes
131,Botswana,56-53-54-49,OTHER(SPECIFY),Yes,110.0,Tonnes,Yes,110.00,Tonnes,4800.0,No,No,No,No,No,Yes,0.0,NaN,No,NaN,NaN,No,Yes,Yes,Yes
132,Botswana,56-53-54-49,SORGHUM,Yes,3675.0,Tonnes,Yes,3675.00,Tonnes,2700.0,No,No,No,No,No,Yes,0.0,NaN,No,NaN,NaN,No,Yes,Yes,Yes
133,Botswana,01-08-40-07,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,Yes,Yes
134,Botswana,14-31-43-40,OKRO,Yes,200.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,150.0,Numbers,No,NaN,NaN,Yes,No,No,No
135,Botswana,14-31-43-40,GREEN VEGETABLE,Yes,840.0,Bale / Bundle,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,640.0,Bale / Bundle,No,NaN,NaN,Yes,No,No,No
136,Botswana,37-39-15-65,OTHER SPECIFY,Yes,30.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,Numbers,No,NaN,NaN,No,No,No,Yes
137,Botswana,37-39-15-65,MAIZE,Yes,2.0,Wheelbarrow,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Wheelbarrow,No,NaN,NaN,No,No,No,Yes
138,Botswana,37-39-15-65,SORGHUM,Yes,1.0,Other (please specify),No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Other (please specify),No,NaN,NaN,No,No,No,No
139,Botswana,45-44-88-31,BEANS/COWPEA,Yes,3.0,50 kg bag,Yes,1.00,50 kg bag,1000.0,Yes,No,No,No,No,No,1.0,10kg bag,Yes,2.0,50 kg bag,No,No,No,Yes
140,Botswana,45-44-88-31,MAIZE,Yes,5.0,50 kg bag,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,25kg bag,Yes,5.0,50 kg bag,No,No,No,Yes
141,Botswana,79-34-34-89,SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,Yes,No,Yes
142,Botswana,29-41-63-44,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,No,No
143,Botswana,58-42-18-32,APPLE,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
144,Botswana,58-42-18-32,MANGO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
145,Botswana,58-42-18-32,BANANA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
146,Botswana,09-31-11-33,OTHER SPECIFY,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,Yes,Yes
147,Botswana,09-31-11-33,BEANS/COWPEA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,Yes,Yes
148,Botswana,09-31-11-33,GUINEA CORN/SORGHUM,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No,Yes,Yes
149,Botswana,04-26-72-23,GREEN VEGETABLE,Yes,5.0,Bale / Bundle,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Bale / Bundle,No,NaN,NaN,Yes,No,No,No
150,Botswana,04-26-72-23,SUGAR CANE,Yes,2.0,Numbers,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,Numbers,No,NaN,NaN,Yes,No,No,No
151,Botswana,04-26-72-23,GUAVA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
152,Botswana,04-26-72-23,LEMON,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
153,Botswana,04-26-72-23,MANGO,Yes,90.0,Numbers,Yes,70.00,Numbers,1.0,Yes,No,No,No,No,No,20.0,Numbers,No,NaN,NaN,Yes,No,No,No
154,Botswana,04-26-72-23,AVOCADO PEAR,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
155,Botswana,04-26-72-23,BANANA,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No
156,Botswana,06-64-69-84,IRISH POTATO,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,Yes,No,No,No

### 2.2 Creating Individual-Level Features

In [62]:
individual_features = []

for country, base_path in COUNTRIES.items():
    #NO CLEANING NECESSARY 

    #CLEANING NECESSARY


    #SOME FEATURES ARE NOT AVAILABLE FOR EACH COUNTRY: optional_merges solves this as it only merges available features
    optional_merges = [
    ]

    df_help = None

    for df, keys, how in optional_merges:
        if df is not None:
            if df_help is None:
                df_help = df
            else:
                df_help = df_help.merge(df, on=keys, how=how)

    individual_features.append(df_help)

df_individual_features = pd.concat(individual_features, ignore_index=True)

ValueError: All objects passed were None

## 3. Write clean data to data/raw folder

In [ ]:
df.to_csv(config.PROCESSED_DATA_DIR / "clean_data.csv", index=False)